### ISSUE TITLE
Skipping the gridpack generation and only parsing the fragments

### ISSUE THREAD

**Issue by sihyunjeon** [cms-PdmV/GridpackMachine#23]
It would be nice if we can (for some of the samples) skip gridpack generation part and just use the one existing in CVMFS if applicable.

We might have some cases where we want to use the same gridpack but only change the fragments. Then everything in [1] is ignorable except things related to "fragment".

[1] https://github.com/cms-PdmV/GridpackFiles/blob/master/Cards/MadGraph5_aMCatNLO/DY/DYGto2LG-1Jets_MLL-4to50_PTG-100to200_amcatnloFXFX-pythia8/DYGto2LG-1Jets_MLL-4to50_PTG-100to200_amcatnloFXFX-pythia8.json

Can we create a channel that takes following arguments from json file
```
"parent_process" : DY
"parent_dataset" : "DYGto2LG-1Jets_MLL-4to50_PTG-100to200_amcatnloFXFX-pythia8"
```

and make the python script to search for

`/cvmfs/cms.cern.ch/phys_generator/gridpacks/PdmV/Run3Summer22/DY/DYGto2LG-1Jets_MLL-50_PTG-50to100_amcatnloFXFX-pythia8_*`

And use this gridpack instead of submitting a new gridpack job and only make new fragments with new prepid?

**Comment by sihyunjeon** [comment]
@agrohsje @cvico @ggonzr

**Comment by agrohsje** [comment]
i like the idea. but how would you trigger this possibility vs generation of gridpack ?

**Comment by sihyunjeon** [comment]
Very naively, it is possible to do something like
```
try dict['parent_process']:
    SKIPGRIDPACK
except:
    SUBMITGRIDPACK
```
with python, since the real DY one that needs gridpack won't have "parent_process" set in the dictionary. Of course this is not really "secure/well" coding so need to talk to geovanny for more details since he might have better ways to deal with it. But I think there is still ways to click the same button in the web interface, but do two different things (1) normal workflow making gridpacks, waiting, and making prepids (2) skipping gridpacks and making prepids directly.

**Comment by ggonzr** [comment]
Hi @agrohsje, @Cvico, @sihyunjeon,

I have opened a PR with the current progress for this feature. If you want to check it, it is available in the [development](https://cms-pdmv-dev.web.cern.ch/gridpack/) version. There are some points I would like to discuss with you:

1. The Gridpack is reused properly but there is some information required by the application that is not available in the example JSON, for example, the data related to the ‘run card’ and the ‘customize card’. If you click these buttons, you will receive a server error. How can we fill this information? Is okay if we display a message that this information is not available due to the Gridpack was reused?

2. Currently, if there is more than one Gridpack after filtering possible candidates to reuse, the most recent is chosen. Also, I included an email to notify about the Gridpack that was reused. In order to avoid extra stops and resets, I suggest to continue using this approach instead of raising a failure if there is more than one candidate.

If you require more granularity for choosing a Gridpack, please include a regex in the file name section that exactly matches the one you require. Following the test example, let’s say you have the following Gridpacks in `NewTest` process and you require only the one linked with `slc7` and `CMSSW 12_*` release:

- DummyTest_madgraphMLM-pythia8_slc8_amd64_gcc10_CMSSW_13_0_1_tarball.tar.xz
- DummyTest_madgraphMLM-pythia8_slc7_amd64_gcc10_CMSSW_12_4_8_tarball.tar.xz

If you provide `NewTests/DummyTest_madgraphMLM-pythia8.*_slc7_.*_CMSSW_12_.*` in the `gridpack_path` you will get only the second in the example. 

Please let me know if this proposal meets your requirement

Best,
Geovanny

**Comment by sihyunjeon** [comment]
Hi Geovanny,
1. If it's possible it would be nice to show when clicking the cards, "which gridpack" was reused. Though, server error is still fine if you need to hard wire the code here and there to make this displayed.
2. The "most recent one" => Do you mean the gridpack that was copied to eos area more recently? So instead of choosing latest version of OS/CMSSW the logic is to define which gridpack to choose based on the date it was created?

**Comment by ggonzr** [comment]
Hi Sihyun, thanks for the feedback,

Related to your reply:

1. Okay, I am going to check if I can query the DB to match all the remaining information based on the archive used. Otherwise, I will return a message explaining why this information is not available.

2. The current logic searches in the requested folder (/eos area) if there are Gridpacks, if so, it retrieves the last modification date and the filename per each element. Then, the files are filtered only to pick those whose file name complies with the regex given and then, if there is more than one file, the most recent is taken.

**Comment by sihyunjeon** [comment]
Hi @ggonzr sorry if i didn't explain clearly,

1. I meant "clicking card" -> "this submission reused gridpack /cvmfs/blahblah/area/ please check the corresponding gridpack for card details" : If this message can be displayed, it's fine, you don't need to look for the whole DB to link the cards with whole proper information (it would be nice but not so necessary! don't want to waste your time too much) if this was what you meant.

2. That should work I think. I am not sure what situations we will encounter but for now i think it is reasonable

**Comment by ggonzr** [comment]
I have included a new update to retrieve the cards for reused Gridpacks and handle errors when retrieving this element. Please check the development version and let me know if something is missing.

Thanks,
Geovanny

**Comment by Cvico** [comment]
Hi, I've checked and indeed it see it works! I get the following message:
Gridpack reused: /eos/project/c/cmsweb/www/pdmv-web-test/pdmv_gridpacks/Run3Summer22/MadGraph5_aMCatNLO/NewTests/DummyTest_madgraphMLM-pythia8_slc7_amd64_gcc10_CMSSW_12_4_8_tarball.tar.xz

**Comment by ggonzr** [comment]
The last update includes some comment lines to display the Gridpack linked to the `run_card` or the `customize_card`. @agrohsje is okay to display them also for Powheg gridpacks like in these examples [`run_card`](https://cms-pdmv-dev.web.cern.ch/gridpack/api/get_run_card/1686216010792), [`customize_card`](https://cms-pdmv-dev.web.cern.ch/gridpack/api/get_customize_card/1686216010792)?

**Comment by ggonzr** [comment]
I would like to know if the following situation could happen in production (normal) operations. 

Is it possible that two Gridpack requests in the application create the same output file? For instance, for development/test purposes, I created another Gridpack request ([1697186100360](https://cms-pdmv-dev.web.cern.ch/gridpack/?_id=1697186100360)) via the web page that uses the same input data as ([1696829501686](https://cms-pdmv-dev.web.cern.ch/gridpack/?_id=1696829501686)), the only difference is the number of events and number of resources used in the creation. The output file is the same and overwrites the first request output.

Currently, the application spots that two Gridpacks are linked with the same output file that was created with a batch job and raises an issue when cards are retrieved for Gridpacks that reused this artifact (e.g: [1697127952179](https://cms-pdmv-dev.web.cern.ch/gridpack/api/get_run_card/1697127952179)). So, if this duplicated situation happens in production operations, how should we deal with it?

**Comment by ggonzr** [comment]
> I would like to know if the following situation could happen in production (normal) operations.
> 
> Is it possible that two Gridpack requests in the application create the same output file? For instance, for development/test purposes, I created another Gridpack request ([1697186100360](https://cms-pdmv-dev.web.cern.ch/gridpack/?_id=1697186100360)) via the web page that uses the same input data as ([1696829501686](https://cms-pdmv-dev.web.cern.ch/gridpack/?_id=1696829501686)), the only difference is the number of events and number of resources used in the creation. The output file name is the same and overwrites the first request output.
> 
> Currently, the application spots that two Gridpacks are linked with the same output file that was created with a batch job and raises an issue when cards are retrieved for Gridpacks that reused this artifact (e.g: [1697127952179](https://cms-pdmv-dev.web.cern.ch/gridpack/api/get_run_card/1697127952179)). So, if this duplicated situation happens in production operations, how should we deal with it?

According to the stakeholders, this situation could happen but not too often. My understanding about their reply is, in case this happens, the files related to the `run_card` and `customize_card` will be the same, therefore, it is okay to display these elements using the most recent Gridpack or the original Gridpack used as model for the reused one.

**Comment by ggonzr** [comment]
I have included some updates to store the ID of the original gridpack reused instead of just including its output file name and this should solve the last issue. Please test the application and let me know if something is missing. Otherwise, I will merge this feature and update the application on Monday next week.

Best,
Geovanny

**Comment by ggonzr** [comment]
Update: There was an issue when a Gridpack input file was reused and there was no Gridpack request linked to its generation (‘parent’ Gridpack). This raised issues in the application. The following update removes this constraint. 

One point I would like to highlight, if it is not possible to find the ‘parent’ Gridpack for some request that reuses files, it is not possible to display the ‘run’ card or the ‘customize’ card from the application. These actions require some paths that are not provided by the JSON description (e.g: [This](https://github.com/cms-PdmV/GridpackFiles/blob/master/Cards/MadGraph5_aMCatNLO/NewTests/DummyTest_ReuseGridPack_PTLL-40to100_madgraphMLM-pythia8/DummyTest_ReuseGridPack_PTLL-40to100_madgraphMLM-pythia8.json)) to reuse a Gridpack.
